services:
  postgres:
    image: postgres:16
    container_name: rg-postgres
    environment:
      POSTGRES_USER: repoguard
      POSTGRES_PASSWORD: repoguard
      POSTGRES_DB: repoguard
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: rg-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./docker-data/redis:/data
