name: Smoke
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ stage-5-ci-smoke ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: rg
          POSTGRES_PASSWORD: rgpass
          POSTGRES_DB: repoguardian
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U rg"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20
      redis:
        image: redis:7
        ports: ["6379:6379"]
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install web deps
        run: pnpm -C web install
      - name: Create .env.local
        run: |
          cat > web/.env.local <<'EOF'
          DATABASE_URL=postgresql://rg:rgpass@localhost:5432/repoguardian
          REDIS_URL=redis://localhost:6379
          NEXT_PUBLIC_APP_NAME=RepoGuardian
          EOF
      - name: Build web
        run: pnpm -C web build
      - name: Start web
        run: pnpm -C web start &
        env:
          PORT: 3000
      - name: Wait for /api/health
        run: |
          for i in {1..30}; do
            curl -fsS http://localhost:3000/api/health && exit 0
            sleep 2
          done
          echo "Health check failed" && exit 1
