name: Worker Smoke
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ stage-6-worker-health ]
jobs:
  worker_smoke:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports: ["6379:6379"]
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install worker deps
        run: pnpm -C worker install
      - name: Start worker
        run: pnpm -C worker dev &
        env:
          REDIS_URL: redis://localhost:6379
          WORKER_PORT: 9100
      - name: Wait for health
        run: |
          for i in {1..30}; do
            curl -fsS http://localhost:9100/health && exit 0
            sleep 2
          done
          exit 1
      - name: Enqueue dummy job
        id: enqueue
        run: |
          JOB_ID=$(curl -fsS -X POST http://localhost:9100/enqueue/dummy -H 'content-type: application/json' -d '{}' | jq -r .jobId)
          echo "job_id=$JOB_ID" >> $GITHUB_OUTPUT
      - name: Wait job completion
        run: |
          for i in {1..60}; do
            STATUS=$(curl -fsS http://localhost:9100/job/${{ steps.enqueue.outputs.job_id }} | jq -r .status)
            echo "status=$STATUS"
            [ "$STATUS" = "completed" ] && exit 0
            sleep 1
          done
          exit 1
      - name: Check metrics
        run: |
          curl -fsS http://localhost:9100/metrics | grep -E 'jobs_total|job_duration_seconds'
